title: Soponka.sk
description: The cutest drawings on the web...
url: soponka.sk
email: petonosal@gmail.com
github_username:  PetkoNosal

# Build settings
markdown: kramdown

# Exclude from processing.
exclude:
  - .idea/
  - .gitignore
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.locl
